# Generated by Django 5.1.6 on 2025-03-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=50)),
            ],
        ),
    ]
