name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m venv myenv
        source myenv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django Migrations
      run: |
        source myenv/bin/activate
        python manage.py migrate

    - name: Run Tests
      run: |
        source myenv/bin/activate
        python manage.py test
